config/routes.rb
Rails.application.routes.draw do
  get 'portfolio/index'

  get 'portfolio/show'
  get '/projects/:id', to: 'portfolio#show'

  namespace :admin do
    resources :categories
  end

  namespace :admin do
    resources :projects
  end

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'portfolio#index'
  resources :projects, :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :projects
	has_many :category_images
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	scope :visible, -> {where(visible: true)}


end

app/models/category_image.rb
class CategoryImage < ActiveRecord::Base
  belongs_to :category
  	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/education.rb
class Education < ActiveRecord::Base
	has_many :programs
end

app/models/experience.rb
class Experience < ActiveRecord::Base
		scope :primary, -> {where(primary: true)}
		scope :secondary, -> {where(primary: false)}

end

app/models/goodproject_video.rb
class GoodprojectVideo < ActiveRecord::Base
  belongs_to :project
     has_attached_file :video, :styles => { :medium => "300x300>", :thumb => "100x100>" }#, :processors => [:transcoder]
     	validates_attachment_content_type :video, :content_type => ['video/mp4']



end

app/models/program.rb
class Program < ActiveRecord::Base
  belongs_to :education
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_and_belongs_to_many :categories
	has_many :project_images
	has_many :project_videos
	has_many :goodproject_videos
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	scope :visible, -> {where(visible: true)}
	scope :initial, -> {where(initial: true)}

end

app/models/project_image.rb
class ProjectImage < ActiveRecord::Base
  belongs_to :project
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/project_videos.rb
class ProjectVideo < ActiveRecord::Base
  belongs_to :project
   has_attached_file :video, :styles => { :medium => "300x300>", :thumb => "100x100>" }
   validates_attachment_content_type :video, :content_type => /\Avideo\/.*\Z/


end

app/models/sample.rb
class Sample < ActiveRecord::Base
end

app/models/skill.rb
class Skill < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /admin/projects
  # GET /admin/projects.json
  def index
    @projects = Project.all
  end

  # GET /admin/projects/1
  # GET /admin/projects/1.json
  def show
  end

  # GET /admin/projects/new
  def new
    @project = Project.new
  end

  # GET /admin/projects/1/edit
  def edit
  end

  # POST /admin/projects
  # POST /admin/projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to [:admin, @project], notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/projects/1
  # PATCH/PUT /admin/projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to [:admin, @project], notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/projects/1
  # DELETE /admin/projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to admin_projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :productionYear)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
   before_action :set_project, only: [:show]
   skip_before_action :verify_authenticity_token, only: [:show]
   # before_action :set_project, only: [:show, :edit, :update, :destroy]
  def index
  	    @projects = Project.all
  	    @categories = Category.all
  	    @educations = Education.all
  	    @experiences = Experience.all 
  	    @contact = Contact.all
  	    @programs = Program.all 
  	    @skills = Skill.all 

  end

  def show
 

 respond_to do |format|
      format.html
      format.xml { render :xml => @project.to_xml }
      format.js {} #{render action: 'portfolio/project', object: @project}
      format.json {}#{ render action: 'show', status: :created, location: @skill }
    end
  end
   private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :productionYear)
    end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  #before_action :set_sample, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @samples = Sample.all
    respond_with(@samples)
  end

  def show
    respond_with(@sample)
  end

  def new
    @sample = Sample.new
    respond_with(@sample)
  end

  def edit
  end

  def create
    @sample = Sample.new(sample_params)
    @sample.save
    respond_with(@sample)
  end

  def update
    @sample.update(sample_params)
    respond_with(@sample)
  end

  def destroy
    @sample.destroy
    respond_with(@sample)
  end

  private
    def set_sample
      @sample = Sample.find(params[:id])
    end

    def sample_params
      params.require(:sample).permit(:title, :blurb)
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/portfolio/_categories.html.erb
<% category = @category %>

		<div class = "sectionContainer ">
			<h1><%= category.name %></h1>
			<p><%= category.description %></p>

			
			 <div class = "imageContainer">

			 	<div class = "flexSlider">
		    <!-- Slides Container -->
		    		      			 	<% category.projects.initial.each do |project|%>
		    		      			 	

		    <ul class = "slides">
		   <%#= project.title %>
		      			 	<% project.project_images.each do |metaImage|%>
		        	<li class = "projectImageContainer"><%= image_tag metaImage.image.url %></li>
		        <%end%>

		    </ul>
		     			        <%end%>

				</div>

			 </div>

			 <ul class = "projectList">
			 	<% category.projects.visible.each do |project|%>
			 	<% @project = project %>
<li>		    	<%= link_to "#{project.title}", project_path(@project, format: :js), remote: true %>
			 	</li>			 	
			 	<%end%>
			</ul>



			</div>

app/views/portfolio/_navigation.html.erb
<!-- <header class= "home-head"> Jason Scott Rosen || Portfolio </header>
 -->
 <div class = "topNav">
<ul class = "menu" id = "fp-nav">

	<li class = "menuItem" data-menuanchor="top"> 		<a href="#top"><%= image_tag("logo_small_brown.png", size: 100)%></a> </li>
	<!-- <li class = "menuItem" data-menuanchor="about"> 	<a href="#about"><p>ABOUT	</p></a>	 </li> -->
	<li class = "menuItem" data-menuanchor="projects"> <a href="#projects"><p>PROJECTS </p></a>

	 				 </li>
	<li class = "menuItem" data-menuanchor="resume"> 	<a href="#resume"><p>RESUME   </p>  </a>	 </li>
</ul>
</div>

app/views/portfolio/_project.html.erb
<% project = @project %>

 <!-- <ul class = "slides"> -->
		   

		    <!-- </ul> -->
<!--  -->
		    <div class = "sectionContainer ">
			<h1><%= project.title %></h1>

			<div class = "projectDescription">
			 	<p><%= project.description %></p>
			 			 	
			 			 	<%# category.projects.visible.each do |project|%>
			 			 	<%# @project = project %>
			 			 	
			 			 	<%#end%>
			 </div>
			 <div class = "imageContainer">

			 	<div class = "flexSlider">
		    <!-- Slides Container -->
		    		      			 	

		    <ul class = "slides">
		    		<% project.project_images.each do |image|%>

		        	<li class = "projectImageContainer"><%= image_tag image.image.url %></li>
		        <%end%>

		    </ul>
		     			        <%#end%>

				</div>

			 </div>


				<div class = "videoContainer">
					<% project.goodproject_videos.each do |video| %>
					<%= video_tag "#{video.name}", video.video.url, controls: true %>
					<% end %>
				</div>

			</div>

app/views/portfolio/_projects.html.erb
<div class = "projectContainer" id = "projectContainer">
 <div class = "imageContainer">
 </div>

<div class = "projectDescription">
	<p>this is the project description section and will extend a lot of lines down the right edge of the screen</p>
</div>
</div>

app/views/portfolio/index.html.erb
	<div class="section" id = "topSection" data-anchor="top" >
				<%# image_tag("site_bg_0.jpg")%>

<!-- <div class "sectionContainer"> -->
	<div id = "topContainer"> 

<%# video_tag("overcast.mp4", autoplay:true, controls: false, muted: true, autobuffer: true, id: "bgVid", :loop => true) %>

<!-- </video> --><div class = "videoOverlay">
<span class = "topHeader"> <h1>about  </h1>  </span>
	<span class = "aboutText">	<p>This is a select portfolio of  creative projects that explore my investigations into interdisciplinary multimedia production. I am interested in synthesizing practices as varied as experience design, art direction, critical theory, game design and performance documentation to create new modalities of storytelling in an increasingly digitized age.</p>

<p>Much of my artistic practice touches upon themes regarding the social and biological implications of life in the anthropocene, both critically and aesthetically. I deploy my creative abilities as well as intellectual inquiries to client's projects as well, as a producer and strategist. i invite collaboration.</p>
<p>Please reach out and say hello!
</p></span>
	<span class ="topFooter">  <a class= "topLink" href="http://instagram.com/goldencalf" target ="_blank"> Instagram  </a> <a href="https://www.linkedin.com/pub/jason-rosen/23/b64/182" target ="_blank" > LinkedIn</a>   </span>
</div>
</div>
				<!-- </div> -->

<%#= video_tag("Love OutofBounds-SD.mp4", controls: false, muted: true, autoplay: true) %>


		
	</div>

	<!-- <div class="section" data-anchor="about" >
<div class = "sectionContainer">
		
</div>

	</div> -->
	

	<div class="section" data-anchor="projects">

			<ul class = "projectList fp-slidesNav right" id ="homeProjectList">
					<% @projects.visible.each do |project| %>
					<li class = "menuItem"> <a href = #> <%=project.title.upcase%> </a> </li>
					<% end %>
				</ul>
				
				<% @projects.visible.each do |project| %>
				<% @project = project %>

				<div class="slide" data-anchor="slide<%=project.id%>" >
		
							<%= render "project", object: project %>
				</div>
							<% end %>
		
	</div>


	<div class="section" id ="Résumé/CV" data-anchor="resume" >

		<div class = "sectionContainer" id = "resumeContainer">
<!-- 			<h1>Résumé/CV</h1>
 -->			<div class = "resumeDiv" id = "primaryExperienceDiv">
				<h1> Primary Experience</h1>
				<ul id = "primaryExperienceList">
					<% @experiences.primary.each do |experience | %>
								<l1>
									<div class = "experienceDiv"> 
																	<h2> <%= experience.employer + "-" %> <%= experience.position %> </h1> 
																	<h2> <%= experience.location%> <%=experience.start.to_s %> <%= experience.end.to_s %> </h2>
																	<p> <%= experience.description %> </p>
												
									</div>
								</l1>
								<%end%>

							</ul>
			</div>
			<div class = "resumeDiv" id = "secondaryResumeDiv" >
				<div id = "educationDiv ">
					<ul class = "educationList">
						<h1> Education</h1>
					<% @educations.each do |education| %>
<li>					<h2> <%= education.institution %> <%= education.graduation.to_s %> </h2>
					</li><ul>					
										<% education.programs.each do |program| %>
					<li>					 <%= program.name%> 
					 					</li> 					<%end%></ul>

					<%end%>
				</ul>
				</div>
				<div class = "skillsWrapper">
														<h1> Skills </h1>

					<div id = "skillsDiv">
									<% @skills.find_in_batches(start: 0, batch_size: 9) do |group|%>
									<div class = "skillsBatch">
										<% group.each do |skill| %>
														<p> <%= skill.name %> </p>
										<% end %>
									</div>
									<% end %>
								 </div></div>

				 <div id = "secondaryExperienceDiv ">
				 					<h1> Other Experience</h1>

				 	<ul id = "secondaryExperienceList">
				 		<% @experiences.secondary.each do |experience| %>
				 					 	<li>
				 					 		<div class = "experienceDiv"> 
				 					 					 						<h2> <%= experience.employer + "-" %> <%= experience.position %> </h2> 
				 					 					 						<h2> <%= experience.location%> <%=experience.start.to_s %> <%= experience.end.to_s %> </h2>
				 					 					 						<p> <%= experience.description %> </p>
				 					 					 	
				 					 					 					</div></li>
				 	
				 					 	<%end%>
				 					 </ul>
				 </div>	
			</div>
					</div>
	</div>

app/views/portfolio/show.html.erb
<% project = @project %>

<h1>Portfolio#show</h1>
<p>Find me in app/views/portfolio/show.html.erb</p>

<%= project.title%>

app/views/portfolio/show.js.erb
$( document ).ready(function() {


$(".slides").html("<%= j (render(partial: 'portfolio/project')) %>");

$('.flexslider').flexslider({
 	animation: "fade",
 	smoothHeight: true
 });




$(window).resize();
});